<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sum_Minus.Entities\Sum_Minus.Entities.csproj" />
    <ProjectReference Include="..\Sum_Minus.Services\Sum_Minus.Services.csproj" />
  </ItemGroup>

</Project>
